Overloaded << operator to print points.
BoostGSoC19/astronomy pull request #107
Opened 2020-02-11 21:42 UTC by NitinK-1999

### Description
Overloaded << operator to print points.

2020-02-12 14:57 UTC, lpranam requested changes
Please remove `\n`

2020-02-14 12:04 UTC, NitinK-1999 commented
> Please remove `\n`

I have removed `\n`. Are there any other changes to be made?

2020-02-14 23:01 UTC, lpranam requested changes
Everything else looks good just some minor coding style changes. Thank you for your contributions.

2020-02-14 23:01 UTC, lpranam commented on include/boost/astronomy/coordinate/io.hpp
> +
nitpicking: no blank lines required

2020-02-14 23:01 UTC, lpranam commented on include/boost/astronomy/coordinate/io.hpp
> +
nitpicking: only single blank line

2020-02-14 23:01 UTC, lpranam commented on include/boost/astronomy/coordinate/io.hpp
> +
nitpicking: only single blank line

2020-02-14 23:01 UTC, lpranam commented on include/boost/astronomy/coordinate/io.hpp
> +
nitpicking: only single blank line

2020-02-14 23:01 UTC, lpranam commented on include/boost/astronomy/coordinate/io.hpp
> +
nitpicking: only single blank line

2020-02-14 23:41 UTC, NitinK-1999 commented
> Everything else looks good just some minor coding style changes. Thank you for your contributions.

Thank you! All the extra spaces have been removed.

2020-02-15 15:43 UTC, lpranam approved these changes

2020-02-15 15:44 UTC, merged