Update fits.hpp to add binary_table to read_extensions() function
BoostGSoC19/astronomy pull request #112
Opened 2020-02-23 11:10 UTC by NitinK-1999

### Description
* The `read_extension()` function supported only `image` and `ascii_table` extensions as parser for `binary_table` had not been developed at the time of writing of the function.
* `binary table` option has been added in this PR.

2020-03-08 06:03 UTC, lpranam requested changes

2020-03-08 06:03 UTC, lpranam commented on include/boost/astronomy/io/fits.hpp
> +            else if (hdu_.back()->value_of<std::string>("XTENSION") == "'TABLE   '")//! Ascii table extension
Nitpicking: we tend to keep a line length <= 100 characters

2020-03-08 06:03 UTC, lpranam commented on include/boost/astronomy/io/fits.hpp
> +            else if (hdu_.back()->value_of<std::string>("XTENSION") == "'BINTABLE'")//! Binary table extension
Nitpicking: we tend to keep a line length <= 100 characters

2020-03-09 04:25 UTC, lpranam requested changes
Can you please remove the "if" in your comments no need of it.

2020-03-09 12:14 UTC, nitink25 commented
> Can you please remove the "if" in your comments no need of it.

Made the change... Thank u for ur review!

2020-03-09 13:32 UTC, lpranam approved these changes
Looks good to me. Thank you for the contribution

2020-09-15 02:22 UTC, lpranam commented
Many things have changed in recent months in the library and this PR is no more needed. Though thank you for taking the time to contribute into the library. We value your time, interest and contribution.

2020-09-15 02:22 UTC, closed without merging