bug fix of cross in arithmetic.hpp
BoostGSoC19/astronomy pull request #126
Opened 2020-04-13 17:42 UTC by RohitRanjangit

### Description
1. Previously, cross generate errors for some coordinate system i.e previous version can't able to identify bu::conversion_factor(plane_angle, meter for cross_product(cartesian point, spherical point) ) in calculation part of code.
2. Now cross returns cross product in requested representation( It returns correct units for every representation).
3. Updated tests for cross product.

### References

### Tasklist

- [x] Add test case(s)
- [x] Ensure all CI builds pass
- [ ] Review and approve

2020-04-13 17:43 UTC, RohitRanjangit commented
@lpranam I made a separate PR for cross product. you may wanna review it.

2020-04-24 21:31 UTC, sarthak2007 requested changes

2020-04-24 21:31 UTC, sarthak2007 commented on include/boost/astronomy/coordinate/arithmetic.hpp
> +    auto cartesian1 = make_cartesian_representation(representation1);
There is no need to convert `representation1` to cartesian as it is already in cartesian.

2020-04-27 08:01 UTC, sarthak2007 approved these changes

2020-05-12 13:39 UTC, lpranam approved these changes

2020-05-12 13:40 UTC, merged