Alt-Az system integrated with boost::units
BoostGSoC19/astronomy pull request #54
Opened 2019-07-21 21:29 UTC by lpranam

### Description
`coordinate/alt_az.hpp` updated to work with unit integrated geometric coordinate system.

### References
closes #53

### Tasklist

- [ ] Add test case(s)
- [ ] Ensure all CI builds pass
- [ ] Review and approve

2019-07-21 22:22 UTC, Ruchika2696 requested changes

2019-07-21 22:22 UTC, Ruchika2696 commented on include/boost/astronomy/coordinate/alt_az.hpp
> +    alt_az(Representation const& representation_data, Differential const& diff)
parameters should be changed to `OtherRepresentation` and `OtherDifferential`

2019-07-21 22:24 UTC, Ruchika2696 commented
missing copy constructor?

2019-07-21 22:29 UTC, Ruchika2696 requested changes
missing copy constructor!!

2019-07-22 11:11 UTC, sarthak2007 requested changes

2019-07-22 11:11 UTC, sarthak2007 commented on include/boost/astronomy/coordinate/alt_az.hpp
> +    alt_az(OtherRepresentation const& representation_data, OtherDifferential const& diff)
Change `diff` to `differential_data` as you used `differential_data` below

2019-07-23 04:02 UTC, Ruchika2696 approved these changes

2019-07-23 04:36 UTC, sarthak2007 approved these changes

2019-07-23 04:47 UTC, merged