Corrections in `alt_az.hpp` and `base_frame`
BoostGSoC19/astronomy pull request #58
Opened 2019-07-25 16:05 UTC by lpranam

### Description
Header file names corrected in `alt_az.hpp`
missing `typename`s added
`get_angular_separation` function corrected in `base_frame`

### Tasklist

- [ ] Ensure all CI builds pass
- [ ] Review and approve

2019-07-25 16:47 UTC, sarthak2007 requested changes
add `typename` also in lines 96-101

2019-07-25 16:54 UTC, sarthak2007 requested changes
I guess `magnitude` function used is giving error as when it is defined in `arithmetic.hpp`, then the coordinate is not converted to `cartesian` but `get_x()` is used

2019-07-25 19:58 UTC, Ruchika2696 approved these changes

2019-07-25 20:30 UTC, lpranam commented
@sarthak2007 that error occurred due to something went wrong in travis. Though where exactly you think the error is in `magnitude`?

2019-07-25 21:23 UTC, sarthak2007 commented
> @sarthak2007 that error occurred due to something went wrong in travis. Though where exactly you think the error is in `magnitude`?

Magnitude function used is giving error as when it is defined in arithmetic.hpp, then the coordinate(that is its argument) is not converted to cartesian but then also get_x() is used

2019-07-26 05:52 UTC, sarthak2007 requested changes

2019-07-26 05:52 UTC, sarthak2007 commented on include/boost/astronomy/coordinate/base_frame.hpp
> +                (magnitude(this->data) * magnitude(other))).value())
Use other.get_data()` instead of `other`

2019-07-26 06:22 UTC, sarthak2007 approved these changes

2019-07-26 07:07 UTC, merged